displayName: Action Table
schemaName: crda0_test_-MMQR5
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - id: MsTeams
      channelId: MsTeams

  recognizer:
    kind: CLICopilotRecognizer

  agentSettings:
    model:
      series: GPT5Chat

    instructions: {}
    web:
      enableWebSearch: true

template: cliagent-1.0.0
language: 1033